### ISSUE TITLE
Error on Jetstream startup `slice bounds out of range`

### ISSUE THREAD

**Issue by eoneal89** [nats-io/jetstream#406] opened 2020-12-10 18:22 UTC
I see this output when trying to restart the Jetstream server:

```
[56] 2020/12/10 17:45:52.383813 [INF] Starting nats-server version 2.2.0-beta.35
[56] 2020/12/10 17:45:52.383850 [INF] Git commit [25a5fa62]
[56] 2020/12/10 17:45:52.383859 [INF] Using configuration file: /etc/nats-config/nats.conf
[56] 2020/12/10 17:45:52.384161 [INF] Starting JetStream
[56] 2020/12/10 17:45:52.393160 [WRN]     _ ___ _____ ___ _____ ___ ___   _   __  __
[56] 2020/12/10 17:45:52.393169 [WRN]  _ | | __|_   _/ __|_   _| _ \ __| /_\ |  \/  |
[56] 2020/12/10 17:45:52.393170 [WRN] | || | _|  | | \__ \ | | |   / _| / _ \| |\/| |
[56] 2020/12/10 17:45:52.393172 [WRN]  \__/|___| |_| |___/ |_| |_|_\___/_/ \_\_|  |_|
[56] 2020/12/10 17:45:52.393173 [WRN]
[56] 2020/12/10 17:45:52.393175 [WRN]                _         _
[56] 2020/12/10 17:45:52.393176 [WRN]               | |__  ___| |_ __ _
[56] 2020/12/10 17:45:52.393178 [WRN]               | '_ \/ -_)  _/ _` |
[56] 2020/12/10 17:45:52.393180 [WRN]               |_.__/\___|\__\__,_|
[56] 2020/12/10 17:45:52.393182 [WRN]
[56] 2020/12/10 17:45:52.393184 [WRN]          JetStream is a Beta feature
[56] 2020/12/10 17:45:52.393185 [WRN]     https://github.com/nats-io/jetstream
[56] 2020/12/10 17:45:52.393188 [INF]
[56] 2020/12/10 17:45:52.393189 [INF] ----------- JETSTREAM -----------
[56] 2020/12/10 17:45:52.393195 [INF]   Max Memory:      22.98 GB
[56] 2020/12/10 17:45:52.393203 [INF]   Max Storage:     93.13 GB
[56] 2020/12/10 17:45:52.393205 [INF]   Store Directory: "/data/jetstream"
[56] 2020/12/10 17:45:52.393227 [INF] ----------------------------------------
[56] 2020/12/10 17:45:52.397118 [INF]   Recovering JetStream state for account "$G"
panic: runtime error: slice bounds out of range [-1:]
goroutine 1 [running]:
github.com/nats-io/nats-server/server.(*msgBlock).readIndexInfo(0xc000218000, 0x0, 0x0)
	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/filestore.go:2293 +0x47a
github.com/nats-io/nats-server/server.(*fileStore).recoverMsgBlock(0xc000210000, 0xb81780, 0xc0001f5ad0, 0x70, 0x0)
	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/filestore.go:445 +0x340
github.com/nats-io/nats-server/server.(*fileStore).recoverMsgs(0xc000210000, 0x0, 0x0)
	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/filestore.go:534 +0x534
github.com/nats-io/nats-server/server.newFileStoreWithCreated(0xc0001b28d0, 0x23, 0x8000000, 0x12a05f200, 0x2540be400, 0xc000194c60, 0x8, 0xc00019a740, 0x1, 0x4, ...)
	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/filestore.go:310 +0x71e
github.com/nats-io/nats-server/server.(*Stream).setupStore(0xc000182a80, 0xc00014f528, 0x0, 0x0)
	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/stream.go:773 +0x27c
github.com/nats-io/nats-server/server.(*Account).AddStreamWithStore(0xc000136000, 0xc0001ed568, 0x0, 0x0, 0x0, 0xc0001ed600)
	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/stream.go:198 +0x5e3
github.com/nats-io/nats-server/server.(*Account).AddStream(0xc000136000, 0xc0001ed568, 0x36a, 0x9e6640, 0xc0001ed550)
	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/stream.go:130 +0x3e
github.com/nats-io/nats-server/server.(*Account).EnableJetStream(0xc000136000, 0x0, 0x28, 0x0)
	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/jetstream.go:536 +0x14ee
github.com/nats-io/nats-server/server.(*Server).EnableJetStream(0xc000120000, 0xc00019c7e0, 0x0, 0xc0001900b0)
	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/jetstream.go:181 +0xbff
github.com/nats-io/nats-server/server.(*Server).Start(0xc000120000)
	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/server.go:1460 +0x78f
github.com/nats-io/nats-server/server.Run(...)
	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/service.go:21
main.main()
	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/main.go:115 +0x141
```

After running a decent sized sustained load against a particular stream (1000 msgs/sec, 700 bytes/msg) for few hours, I increased the load to 1500 msgs/sec, and started to see NATS timeouts for publishing and publish->consumer trip times of several minutes. I stopped all load, restarted the server, and even with minimal load, was still seeing timeouts. I tried to restart the server again to add debug logs, and got the error above.

The stream in question's configuration looks like this:
```
Configuration:
             Subjects: *.*.eventhub.>
     Acknowledgements: true
            Retention: File - Limits
             Replicas: 1
       Discard Policy: Old
     Duplicate Window: 2m0s
     Maximum Messages: unlimited
        Maximum Bytes: 512 MiB
          Maximum Age: 7d0h0m0s
 Maximum Message Size: 8.0 KiB
    Maximum Consumers: unlimited
State:
            Messages: 927,289
               Bytes: 512 MiB
            FirstSeq: 25,267,182 @ 2020-12-09T22:41:56 UTC
             LastSeq: 26,194,470 @ 2020-12-10T17:02:35 UTC
    Active Consumers: 45 
```

This is running the most recent nightly tag image for synadia/nats-server, on a k8s cluster with a 94GiB persistent volume mounted on the `/data` path.

I cannot reliably reproduce the issue from scratch in our other running clusters, but I do have a zipped file of the streams as they exist now on our persistent volume. It's a large file though ~32 MB, so I can't upload it to this issue.

**Comment by ripienaar** [comment] 2020-12-11 11:06
OK I'll try to reproduce, if you have some way to share the 32MB file - like a dropbox share link or something that would be great

I also cant reproduce the slow downs using a benchmark publishing 300000/sec of that size, the startup problem might be due to a ^C or kill -9 at the wrong time that we should look into for sure

**Comment by ripienaar** [comment] 2020-12-11 11:23
wdyt @derekcollison

**Comment by derekcollison** [comment] 2020-12-11 12:05
Yes if you can share via Google Drive or Dropbox that would be very helpful. However I will also look at the code trace for anything obvious.

**Comment by derekcollison** [comment] 2020-12-11 12:12
ok I see where it is having issues, and it is on reading in an index file for a message block underneath the filestore. So if you could package up just the `idx` files that is what we would need.

So for you above would be the following.

`/data/jetstream/$G/streams/<STREAM>/msgs/N.idx`

**Comment by eoneal89** [comment] 2020-12-11 16:35
Here is a link to the zipped `msgs` directory for the bad stream: https://drive.google.com/file/d/1Wb17_ZHQQS-umNyp91vGJ9rAKuNRvfls/view?usp=sharing. Let me know if that doesn't work for you

**Comment by derekcollison** [comment] 2020-12-11 16:39
Thanks will take a look.

**Comment by derekcollison** [comment] 2020-12-14 03:05
Still think there may be an issues with strange short write but the fix is in so that server will not fail and will rebuild index. Once merged should be good.

**Comment by eoneal89** [comment] 2020-12-14 15:20
Thanks, that's great.

If it helps with understanding, I didn't send a kill signal directly to the server. It's a pod running on kubernetes, and I simply updated the stateful set k8s manifest manually and let the k8s orchestration roll the box. I'm pretty sure k8s will send a `SIGINT` code with a grace period before it sends a `SIGKILL`, though I suppose if the box was unresponsive it wouldn't have mattered.

I still haven't been able to reliably reproduce the issue, but I have seen it happen one more time with the corrupted index being written. I'll let you know if I figure out how to reliably reproduce.

**Closed** 2020-12-14 17:00 UTC
